-- Create the AboutUsData table
CREATE TABLE public."AboutUsData" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  
  -- Header
  title_en text null,
  title_ar text null,
  subtitle_en text null,
  subtitle_ar text null,
  
  -- Mission Section
  mission_title_en text null,
  mission_title_ar text null,
  mission_text_en text null,
  mission_text_ar text null,
  
  -- How We Operate Section
  how_it_works_title_en text null,
  how_it_works_title_ar text null,
  how_it_works_text_en text null,
  how_it_works_text_ar text null,
  
  -- Our Commitment Section
  commitment_title_en text null,
  commitment_title_ar text null,
  commitment_text_en text null,
  commitment_text_ar text null,
  
  -- Images
  mission_image_url text null,
  how_it_works_image_url text null,
  commitment_image_url text null,
  
  -- Statistics Numbers
  clinics_number text null,
  distributors_number text null,
  deliveries_number text null,
  
  -- Statistics Labels
  stats_clinics_en text null,
  stats_clinics_ar text null,
  stats_distributors_en text null,
  stats_distributors_ar text null,
  stats_deliveries_en text null,
  stats_deliveries_ar text null,
  
  constraint AboutUsData_pkey primary key (id)
) TABLESPACE pg_default;

-- Insert the default current content covering English and Arabic as the initial DB payload
INSERT INTO public."AboutUsData" (
  title_en, title_ar, 
  subtitle_en, subtitle_ar,
  mission_title_en, mission_title_ar,
  mission_text_en, mission_text_ar,
  how_it_works_title_en, how_it_works_title_ar,
  how_it_works_text_en, how_it_works_text_ar,
  commitment_title_en, commitment_title_ar,
  commitment_text_en, commitment_text_ar,
  mission_image_url, how_it_works_image_url, commitment_image_url,
  clinics_number, distributors_number, deliveries_number,
  stats_clinics_en, stats_clinics_ar,
  stats_distributors_en, stats_distributors_ar,
  stats_deliveries_en, stats_deliveries_ar
) VALUES (
  'About DentQ', 'عن DentQ',
  'Bridging the gap between premier dental distributors and world-class clinics.', 'نسد الفجوة بين أبرز موزعي طب الأسنان والعيادات ذات الطراز العالمي.',
  'Our Mission', 'مهمتنا',
  'DentQ revolutionizes the medical supply chain by acting as the unified platform where clinics can discover, select, and acquire top-tier dental materials from local distributors securely.', 'تُحدث DentQ ثورة في سلسلة توريد المستلزمات الطبية من خلال العمل كمنصة موحدة، حيث يمكن للعيادات اكتشاف واختيار والحصول على مواد طب الأسنان عالية الجودة من الموزعين المحليين بأمان.',
  'How We Operate', 'كيف نعمل',
  'We empower the entire ecosystem. Independent Pickers package your orders straight from the distributors'' warehouses, and our dedicated freelance Drivers ensure swift, secure, and compliant delivery directly to your clinic''s door.', 'نحن نمكّن النظام البيئي بأكمله. يقوم الملتقطون المستقلون بتغليف طلباتك مباشرة من مستودعات الموزعين، ويضمن السائقون المستقلون لدينا توصيلاً سريعًا وآمنًا ومطابقًا للمعايير مباشرة إلى باب عيادتك.',
  'Our Commitment', 'التزامنا',
  'Transparency, velocity, and quality. We stand by our network of distributors and professionals to guarantee that every piece of medical equipment and supply meets the highest regulatory standards.', 'الشفافية والسرعة والجودة. نحن ندعم شبكتنا من الموزعين والمهنيين لضمان أن كل قطعة من المعدات الطبية والإمدادات تلبي أعلى المعايير التنظيمية.',
  '/about_hero.png', '/about_delivery.png', '/DefaultHeroSectionImg.png',
  '50+', '45+', '6K+',
  'Partner Clinics', 'العيادات الشريكة',
  'Top Distributors', 'أبرز الموزعين',
  'Successful Deliveries', 'الطلبات الناجحة'
);
